"use client";
import { ThemeProvider } from "styled-components";
import { defaultTheme } from "@/styles/themes/default";
import { GlobalStyle } from "@/styles/global";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={defaultTheme}>
      <html lang="pt-BR">
        <body>
          {children}
          <GlobalStyle />
        </body>
      </html>
    </ThemeProvider>
  );
}
